#!/bin/bash
if [ -z "$1" ]; then
	echo "Aucun argument"
	break;
fi
LATLONG=$(grep "^$1" OSMTowns.txt | head -n1 | tr '\t' ';')
#tr change le separateur tab en ;
nbreLigne=$(wc -l OSMTowns.txt | cut -d ' ' -f1)
LAT=$(echo "$LATLONG" |cut -d ';' -f3)
LONG=$(echo "$LATLONG" |cut -d ';' -f2)
echo "======>1)Nombre de ville en France : $nbreLigne"
echo "======>2)Latitude et Longitude : La ville $1 a pour latitude $LAT et longitude $LONG"
echo "======>3)Lien :https:://www.openstreetmap.org/#map=18/$LAT/$LONG"
echo "======>4)Liste des villes contenant 'chien' dans leur nom : "
grep "chien" OSMTowns.txt
echo "======>5)Liste des villes contenant 'Chat' ou 'chat' :"
grep -i "chat" OSMTowns.txt
lyon=$(grep "Lyon" OSMTowns.txt | head -n1| tr '\t' ';')
LAT1=$(echo "$lyon" | cut -d ';' -f3)
LONG1=$(echo "$lyon" | cut -d ';' -f2)
dist=$(python3 gps-dist.py $LAT1 $LONG1 $LAT $LONG)
echo "=======>Distance entre $1 et Lyon : $dist"

