#!/bin/bash


LYON=$(grep "Lyon " OSMTowns.txt | head -n 1)
LYON_LAT=$(echo "$LYON" | cut -d$'\t' -f3)
LYON_LONG=$(echo "$LYON" | cut -d$'\t' -f2)

VILLE=$(grep "$1" OSMTowns.txt | head -n 1)
VILLE_LAT=$(echo "$VILLE" | cut -d$'\t' -f3)
VILLE_LONG=$(echo "$VILLE" | cut -d$'\t' -f2)


DISTANCE=$(python3 gps-dist.py $LYON_LAT $LYON_LONG $VILLE_LAT $VILLE_LONG)


#echo "La distance entre Lyon et $1 est de $DISTANCE km"
echo $DISTANCE